version: '2.3'

services:
  app:
    image: node:9.10
    working_dir: /app
    command: npm run dev
    environment:
      - CLEANUP_AT_STARTUP=ALL
    ports:
      - 80:80
    volumes:
      - '../:/app'
      - '/var/run/docker.sock:/var/run/docker.sock'
      # Docker needs to access to the directory where repositories are cloned
      - '/tmp/cqa:/tmp/cqa'

  redis:
    image: redis:3.2.11-alpine
